api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from api.views import *

urlpatterns = [
    path('api-token-auth/', obtain_jwt_token, name='create-token'),
    #re_path('api/(?P<version>(v1|v2))/', include('music.urls'))
    path('auth/login/', LoginView.as_view(), name="auth-login"),
    path('auth/register/', RegisterUsers.as_view(), name="auth-register"),
    path('rest-auth/', include('rest_auth.urls')),
]

app/urls.py
from django.urls import include, path
from .views import general, customer, bike

urlpatterns = [
    path('home/', general.home, name='home'),
    path('', general.FrontPage, name='front_page'),
    
    path('logout', general.logout_user, name='user_logout'),
    path("login", general.login, name='userlogin'),


    path('bike/', include(([

        path('dashboard', bike.BikeDashboard, name='dashboard'),
        path('profile/<pk>', bike.BikeProfile, name='bike_profile'),
        path('orders', bike.DeliveryOrder, name='order_delivery'),
        path('ordersdetails/<pk>', bike.DetailsOrder, name='details'),
        path('orderaccept/<pk>', bike.AcceptOrder, name='accept_order'),
        path('ordercompleted/<pk>', bike.CompleteOrder, name='complete_order'),


   
      
    ], 'app'), namespace='bike')),

    path('customer/', include(([

        path('dashboard', customer.CustomerDashboard, name='dashboard'),
        path('profile/<pk>', customer.CustomerProfile, name='customer_profile'),
        path('order', customer.PlaceOrder, name='place_order'),
        path('ajax/load-subcategories/', customer.load_foodcategory, name='ajax_load_subcategories'),
        path('category', customer.AdCategory, name='category'),
        path('billing/<pk>', customer.MyBilling, name='billing'),
        path('payment/<pk>', customer.PaymentProcess, name='payment'),
        path('done/<pk>', customer.SuccessPayment, name='successpayment'),
        path('history/<pk>', customer.HistoryOrder, name='order_history'),
        path('edit/<pk>', customer.OrderEdit, name='order_edit'),
        path('info/<pk>', customer.InfoEdit, name='info_edit'),
        


        
       
       
    ], 'app'), namespace='customer')),
]

food/urls.py
from django.contrib import admin
from django.urls import include, path
from app.views import general, customer, bike
from django.conf.urls import url
from  django.contrib.auth import login
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('app.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('apiv1/', include('apiV1.urls')),
    path('apiv2/', include('appV2.urls')),
    path('admin/', admin.site.urls),
    path('accounts/signup/customer/', customer.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/bike/', bike.BikeSignUpView.as_view(), name='bike_signup'),

    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    #path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]



if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

app/views/bike.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.contrib.auth.forms import PasswordChangeForm
from ..decorators import bike_required
from ..forms import *
from ..models import *
from django.contrib.messages.views import SuccessMessageMixin





@bike_required
def BikeDashboard(request):
    return render(request, 'bike/dashboard.html')




class BikeSignUpView(CreateView):
    model = User
    form_class = BikeSignUpForm
    template_name = 'registration/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'bikeman'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        p = ProfileBike.objects.get(user=self.request.user.id)
        return redirect('bike:bike_profile', p.id)


def BikeProfile(request, pk):
    template_name = 'bike/bikeprofile.html'
    bike = get_object_or_404(ProfileBike, pk=pk)
    form = BikeProfileForm(request.POST or None, request.FILES or None, instance = bike)
    if request.method == 'POST':
        if form.is_valid():
            p = form.save(commit=False)
            p.save()
            return redirect('bike:dashboard')
    return render(request, template_name, {'form': form})


def DeliveryOrder(request):
    template_name = 'bike/orderhistory.html'
    order = Order.objects.filter(received=False, paid=True).order_by('-created_at')

    
    
    return render(request, template_name, {'order': order})

def DetailsOrder(request, pk):
    template_name = 'bike/orders.html'
    orders = get_object_or_404(Order, pk=pk)
    neworder = orders.id
    order = ProcessOrder.objects.filter(order=orders).first()
    if request.method == 'POST':
       
        p = Order.objects.filter(id=neworder).update(received=True)
        return redirect('bike:accept_order', orders.id)

    return render(request, template_name, {'orders': orders, 'order': order})


def AcceptOrder(request, pk):
    template_name = 'bike/accept.html'
    orders = get_object_or_404(Order, pk=pk)
    neworder = orders.id
    order = ProcessOrder.objects.filter(order=orders).first()
    if request.method == 'POST':
        p = Order.objects.filter(id=neworder).update(shipped=True)
        return redirect('bike:complete_order', orders.id)
    return render(request, template_name, {'orders': orders, 'order': order})


def CompleteOrder(request, pk):
    template_name = 'bike/completed.html'
    orders = get_object_or_404(Order, pk=pk)
    neworder = orders.id
    order = ProcessOrder.objects.filter(order=orders).first()
    if request.method == 'POST':
        p = Order.objects.filter(id=neworder).update(complete=True)
        return redirect('bike:order_delivery')
    return render(request, template_name, {'orders': orders, 'order': order})

app/templates/bike/accept.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
{% include 'registrationheader.html' %}
    

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">

            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                <div class="myspace">

                        <a href="{% url 'bike:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Orders</a></br>

                        <a href="{% url 'bike:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 btn-block mobile_btn yellow">Orders</a></br>

                        
                        <br/><br/>
                    </div>
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>
                    <table class="table table-responsive-md table-dark">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for o in orders.order.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{o.subcategory}}</td>
                                <td style="text-align: center;">{{o.quantity}}</td>
                                <td>₦{{o.subcategory.price}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                        <h6 style="font-size: 12px;"><b>Vendor Name:</b> {{ order.category.name }}</h6>
                        <h6 style="font-size: 12px;"><b>Vendor Address:</b> {{ order.category.address }}</h6>
                        <h6 style="font-size: 12px;"><b>Customer Address:</b> {{orders.shipping_address}}</h6>
                        <h6 style="font-size: 12px;"><b>Phone Number:</b> {{orders.user.profilecustomer.phone_number}}</h6>
                        <h6 style="font-size: 12px;"><b>Order Note:</b> {{orders.ordernote}}</h6>
                        <h6 style="font-size: 12px;"><b>Order Package:</b> {{orders.package.name}}</h6>
                        
                        <form method='POST'>
                        {% csrf_token %}
                        <div id="bottom-wizard">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Bought</button>
                        </div>
                        </form>

                        {% comment %} {% if o.paid == False %}
                                    <a href="{% url 'customer:payment' orders.id %}"><span class="badge badge-danger">Pay Now</span></a>
                                {% else %}
                                <span class="badge badge-warning">Paid</span>
                                {% endif %}
                                {% if orders.received == False %}
                                <span class="badge badge-info">Processing</span>
                                   
                                {% else %}
                                <span class="badge badge-dark">Receieved</span>
                                {% endif %} {% endcomment %}

                    
                </div>
                <!-- /Wizard container -->
            </div>
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/bike/bikeprofile.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                    <a href="{% url 'bike:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                    <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">bike Profile</a></br>
                    <a href="{% url 'bike:order_delivery' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Orders</a></br>

                    <a href="{% url 'bike:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
	                <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Bike Profile</a></br>
	                <a href="{% url 'bike:order_delivery' %}" class="btn_1 btn-block mobile_btn yellow">Orders</a></br>
					<br/><br/>
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>
					
                    <!-- /top-wizard -->
                    <form method="POST" novalidate>
						{% csrf_token %}
						<h2 style='text-align: center; height: 70px;'>USER PROFILE</h2>
                        <input id="website" name="website" type="text" value="">
                        <!-- Leave for security protection, read docs for details -->
                        
						{{form|crispy}}						
						
						
                        <div id="bottom-wizard">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
                        </div>
                        <!-- /bottom-wizard -->
                    </form>
                </div>
                <!-- /Wizard container -->
            </div>
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/bike/completed.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
{% include 'registrationheader.html' %}
    

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">

            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                <div class="myspace">

                        <a href="{% url 'bike:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Orders</a></br>

                        <a href="{% url 'bike:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 btn-block mobile_btn yellow">Orders</a></br>

                        
                        <br/><br/>
                    </div>
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>
                    <table class="table table-responsive-md table-dark">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for o in orders.order.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{o.subcategory}}</td>
                                <td style="text-align: center;">{{o.quantity}}</td>
                                <td>₦{{o.subcategory.price}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                        <h6 style="font-size: 12px;"><b>Vendor Name:</b> {{ order.category.name }}</h6>
                        <h6 style="font-size: 12px;"><b>Vendor Address:</b> {{ order.category.address }}</h6>
                        <h6 style="font-size: 12px;"><b>Customer Address:</b> {{orders.shipping_address}}</h6>
                        <h6 style="font-size: 12px;"><b>Phone Number:</b> {{orders.user.profilecustomer.phone_number}}</h6>
                        <h6 style="font-size: 12px;"><b>Order Note:</b> {{orders.ordernote}}</h6>
                        <h6 style="font-size: 12px;"><b>Order Package:</b> {{orders.package.name}}</h6>
                        
                        <form method='POST'>
                        {% csrf_token %}
                        <div id="bottom-wizard">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Completed</button>
                        </div>
                        </form>

                        {% comment %} {% if o.paid == False %}
                                    <a href="{% url 'customer:payment' orders.id %}"><span class="badge badge-danger">Pay Now</span></a>
                                {% else %}
                                <span class="badge badge-warning">Paid</span>
                                {% endif %}
                                {% if orders.received == False %}
                                <span class="badge badge-info">Processing</span>
                                   
                                {% else %}
                                <span class="badge badge-dark">Receieved</span>
                                {% endif %} {% endcomment %}

                    
                </div>
                <!-- /Wizard container -->
            </div>
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/bike/dashboard.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">
            <div class="col-lg-12">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>

                    <a href="{% url 'bike:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                    <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">bike Profile</a></br>
                    <a href="{% url 'bike:order_delivery' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Orders</a></br>

                    <a href="{% url 'bike:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
	                <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Bike Profile</a></br>
	                <a href="{% url 'bike:order_delivery' %}" class="btn_1 btn-block mobile_btn yellow">Orders</a></br>
					<br/><br/>
					
			    </div>
            </div>
            
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/bike/orderhistory.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
{% include 'registrationheader.html' %}
    

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">

            <div class="col-lg-4">
                <div id="left_form">
                    
                        <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                <div class="myspace">

                        <a href="{% url 'bike:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Orders</a></br>

                        <a href="{% url 'bike:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 btn-block mobile_btn yellow">Orders</a></br>
                        <br/><br/>
                </div>
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>

                    <table class="table table-responsive-md table-dark" style="font-size: 12px;">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Vendor</th>
                            <th scope="col">Package</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for o in order  %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                {% for v in o.order.all|slice:'1'  %}
                                    <td>{{ v.category.name }}</td>
                                {% endfor %}
                                <td>
                                    {% if o.package.name == 'Standard' %}
                                        <span class="badge badge-danger">Standard</span>
                                    {% elif o.package.name == 'Premium' %}
                                        <span class="badge badge-warning">Premium</span>
                                    {% elif o.package.name == 'Normal' %}
                                        <span class="badge badge-primary">Normal</span>                                
                                    {% endif %}
                                </td>
                                <td>
                                {% if o.order.received == True %}
                                    <span class="badge badge-primary">Received</span>
                                {% else %}
                                <a href="{% url 'bike:details' o.id %}"><span class="badge badge-warning">Details</span></a>
                                {% endif %}
                                
                                </td>
                            </tr>

                        {% endfor %}

                        
                        
                        </tbody>
                    </table>
                        

                    
                </div>
                <!-- /Wizard container -->
            </div>
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/bike/orders.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}

{% block content %}
{% include 'registrationheader.html' %}
    

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">

            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                <div class="myspace">

                        <a href="{% url 'bike:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Orders</a></br>

                        <a href="{% url 'bike:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Bike Profile</a></br>
                        <a href="{% url 'bike:order_delivery' %}" class="btn_1 btn-block mobile_btn yellow">Orders</a></br>

                        
                        <br/><br/>
                    </div>
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>
                    <table class="table table-responsive-sm table-dark">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Item</th>
                            <th scope="col">Qty</th>
                            <th scope="col">Price</th>
                          </tr>
                        </thead>
                        <tbody>
                        {% for o in orders.order.all %}
                            <tr>
                                <td>{{forloop.counter}}</td>
                                <td>{{o.subcategory}}</td>
                                <td style="text-align: center;">{{o.quantity}}</td>
                                <td>₦{{o.subcategory.price}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                      </table>
                        <h6 style="font-size: 12px;"><b>Vendor Name:</b> {{ order.category.name }}</h6>
                        <h6 style="font-size: 12px;"><b>Vendor Address:</b> {{ order.category.address }}</h6>
                        <h6 style="font-size: 12px;"><b>Customer Address:</b> {{orders.shipping_address}}</h6>
                        <h6 style="font-size: 12px;"><b>Phone Number:</b> {{orders.user.profilecustomer.phone_number}}</h6>
                        <h6 style="font-size: 12px;"><b>Order Note:</b> {{orders.ordernote}}</h6>
                        <h6 style="font-size: 12px;"><b>Order Package:</b> {{orders.package.name}}</h6>
                        
                        <form method='POST'>
                        {% csrf_token %}
                        <div id="bottom-wizard">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">Accept</button>
                        </div>
                        </form>

                        {% comment %} {% if o.paid == False %}
                                    <a href="{% url 'customer:payment' orders.id %}"><span class="badge badge-danger">Pay Now</span></a>
                                {% else %}
                                <span class="badge badge-warning">Paid</span>
                                {% endif %}
                                {% if orders.received == False %}
                                <span class="badge badge-info">Processing</span>
                                   
                                {% else %}
                                <span class="badge badge-dark">Receieved</span>
                                {% endif %} {% endcomment %}

                    
                </div>
                <!-- /Wizard container -->
            </div>
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}