api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from api.views import *

urlpatterns = [
    path('api-token-auth/', obtain_jwt_token, name='create-token'),
    #re_path('api/(?P<version>(v1|v2))/', include('music.urls'))
    path('auth/login/', LoginView.as_view(), name="auth-login"),
    path('auth/register/', RegisterUsers.as_view(), name="auth-register"),
    path('rest-auth/', include('rest_auth.urls')),
]

app/urls.py
from django.urls import include, path
from .views import general, customer, bike

urlpatterns = [
    path('home/', general.home, name='home'),
    path('', general.FrontPage, name='front_page'),
    
    path('logout', general.logout_user, name='user_logout'),
    path("login", general.login, name='userlogin'),


    path('bike/', include(([

        path('dashboard', bike.BikeDashboard, name='dashboard'),
        path('profile/<pk>', bike.BikeProfile, name='bike_profile'),
        path('orders', bike.DeliveryOrder, name='order_delivery'),
        path('ordersdetails/<pk>', bike.DetailsOrder, name='details'),
        path('orderaccept/<pk>', bike.AcceptOrder, name='accept_order'),
        path('ordercompleted/<pk>', bike.CompleteOrder, name='complete_order'),


   
      
    ], 'app'), namespace='bike')),

    path('customer/', include(([

        path('dashboard', customer.CustomerDashboard, name='dashboard'),
        path('profile/<pk>', customer.CustomerProfile, name='customer_profile'),
        path('order', customer.PlaceOrder, name='place_order'),
        path('ajax/load-subcategories/', customer.load_foodcategory, name='ajax_load_subcategories'),
        path('category', customer.AdCategory, name='category'),
        path('billing/<pk>', customer.MyBilling, name='billing'),
        path('payment/<pk>', customer.PaymentProcess, name='payment'),
        path('done/<pk>', customer.SuccessPayment, name='successpayment'),
        path('history/<pk>', customer.HistoryOrder, name='order_history'),
        path('edit/<pk>', customer.OrderEdit, name='order_edit'),
        path('info/<pk>', customer.InfoEdit, name='info_edit'),
        


        
       
       
    ], 'app'), namespace='customer')),
]

food/urls.py
from django.contrib import admin
from django.urls import include, path
from app.views import general, customer, bike
from django.conf.urls import url
from  django.contrib.auth import login
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('app.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('apiv1/', include('apiV1.urls')),
    path('apiv2/', include('appV2.urls')),
    path('admin/', admin.site.urls),
    path('accounts/signup/customer/', customer.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/bike/', bike.BikeSignUpView.as_view(), name='bike_signup'),

    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    #path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]



if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

app/views/customer.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.contrib.auth.forms import PasswordChangeForm
from ..decorators import customer_required
from ..forms import *
from ..models import *
from django.contrib.messages.views import SuccessMessageMixin
import random
import string
from decimal import Decimal



def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))




@customer_required
def CustomerDashboard(request):
    return render(request, 'customer/dashboard.html')




class CustomerSignUpView(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = 'registration/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'customer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        p = ProfileCustomer.objects.get(user=self.request.user.id)
        return redirect('customer:customer_profile', p.id)






def CustomerProfile(request, pk):
    template_name = 'customer/editprofile.html'
    customer = get_object_or_404(ProfileCustomer, pk=pk)
    form = CustomerProfileForm(request.POST or None, request.FILES or None, instance = customer)
    if request.method == 'POST':
        if form.is_valid():
            p = form.save(commit=False)
            p.save()
            messages.success(request, "Your Profile Was Updated Successfully...")
            return redirect('customer:dashboard')
    return render(request, template_name, {'form': form})


def load_foodcategory(request):
    category_id = request.GET.get('category')
    subcategory = SubCategory.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'general/order_options.html', {'subcategory': subcategory})








@login_required
def AdCategory(request):
    template_name = 'customer/addcategory.html'
    #form = ProcessFoodForm()
    #form.fields['name'] = forms.ModelChoiceField(Category.objects.all())
    category = Category.objects.all()
    if request.method == 'POST':
        
        form = ProcessFoodForm(request.POST or None)
        if form.is_valid():
            request.session['name'] = request.POST['name']
            #order = request.POST.get('category')
            return redirect('customer:place_order')
           
    return render(request, template_name, {'category': category})




@customer_required
def PlaceOrder(request):
    template_name = 'customer/placeorder.html'
    user = request.user
    orderuser = User.objects.get(id=request.user.id)
    name = request.session.get('name')
    form = SubCategoryFormset()

    if request.method == 'GET':
        for formset in form:
            formset.fields['name'] = forms.ModelChoiceField(SubCategory.objects.filter(category=name))
    
    elif request.method == 'POST':  
        formorder = OrderCreateForm(request.POST)
        formset = SubCategoryFormset(request.POST) 

        if formorder.is_valid() and formset.is_valid():
            order = formorder.save(commit=False)
            order.ref_code = create_ref_code()
            order.user = user
            #order.user = orderuser
            order.save()

                
            for form in formset:
                sub = form.cleaned_data.get('name')
                quantity = form.cleaned_data.get('quantity')
                subcategory = SubCategory.objects.get(id=sub)
                
                if subcategory:
                    ProcessOrder(subcategory=subcategory, order=order, user=user, quantity=quantity).save()
                    
            return redirect('customer:billing', order.id)
            

         
    context = {'form': form}

    
   
    return render(request, template_name, context)

@customer_required
def MyBilling(request, pk):
    template_name = 'customer/order.html'
    order = get_object_or_404(Order, pk=pk, paid=False)  
    item = order.order.all() 
    total_prices = sum((items.subcategory.price * items.quantity) for items in item)
    form = CheckoutForm()
    context = {'form': form, 'order': order, 'total_prices': total_prices,}
    if request.method == 'POST':  
        form = CheckoutForm(request.POST, instance=order)
        if form.is_valid():
            package = form.cleaned_data.get('package')
            shipping_address = form.cleaned_data.get('shipping_address')
            ordernote = form.cleaned_data.get('ordernote')
            pck = PackageType.objects.get(id=package.id)
            grand_total_price = total_prices + pck.price
            order = form.save(commit=False)                
            order.shipping_address = shipping_address
            order.ordernote = ordernote
            order.package = pck
            order.total_price = grand_total_price
            order.save()

            return redirect('customer:payment', order.id)

    return render(request, template_name, context)
        
@customer_required
def PaymentProcess(request, pk):
    order = get_object_or_404(Order, id=pk, paid=False)

    print(order.total_price)
    templates_name = 'customer/payment.html'
    return render(request, templates_name, {'order': order})

 

@customer_required
def SuccessPayment(request, pk):

    order = get_object_or_404(Order, pk=pk)

    Order.objects.filter(pk=order.id).update(paid=True)
    return render(request, 'customer/successpayment.html')

@customer_required
def HistoryOrder(request, pk):
    template_name = 'customer/orderhistory.html'
    order = Order.objects.filter(user=request.user).order_by('-created_at')
    return render(request, template_name, {'order': order},)


@customer_required
def OrderEdit(request, pk):
    template_name = 'customer/editorder.html'
   

    order = get_object_or_404(Order, pk=pk, paid=False)


    results = order.order.all()

    
    form_list = [OrderEditForm(instance=x, prefix=str(x.id)) for x in results]
    

    if request.method == 'POST':
        form_list = [OrderEditForm(request.POST, instance=x, prefix=str(x.id)) for x in results]
        
        if all(form.is_valid for form in form_list):
            for form in form_list:
                form.save()
            return redirect('customer:payment', order.id)
        else:
            form_list = [OrderEditForm(instance=x, prefix=str(x.id)) for x in order]
    return render(request, template_name, {'form_list':form_list})






@customer_required
def InfoEdit(request,pk):
    template_name = 'customer/editorderinfo.html'
    order = get_object_or_404(Order, pk=pk, paid=False)
    item = order.order.all() 
    total_prices = sum((items.subcategory.price * items.quantity) for items in item)
    #print(total_prices)
    
    form = CheckoutForm(request.POST or None, instance=order)
    if request.method == 'POST':
        if form.is_valid():
            package = form.cleaned_data.get('package')
            pck = PackageType.objects.get(id=package.id)
            p = form.save(commit=False)
            p.total_price  = pck.price + total_prices
            p.save()
            return redirect('customer:payment', order.id)
    return render(request, template_name, {'form': form})

app/templates/customer/addcategory.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}
<style>
.btn-default{
background-color: #68889E;
color: red;
border-color: #2F3E48;
}
 
.btn-default:hover, .btn-default:focus, .btn-default:active, .btn-default.active, .open .dropdown-toggle.btn-default {
background-color: #2F3E48;
color:#FFF;
border-color: #31347B;
}

</style>

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>

                    <div class="myspace">
                    
                        <a href="{% url 'customer:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase mt-1" target="_parent">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>

                        <a href="{% url 'customer:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 btn-block mobile_btn yellow">Order History</a></br>
                    
                    </div>  

			    </div>
            </div>
            <div class="col-lg-8 col-md-5">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>

                    <form method="POST">
                        {% csrf_token %}
                        
                        <div class="form-group col-sm-6">

                            <label>Pick Carteen, Store or Market</label>
                        
                            <select class="selectpicker" name='name' data-live-search="true">
                                
                                {% for c in category  %}

                                    <option value="{{ c.id }}" data-tokens="{{ c.name }}">{{ c.name|title }}</option>

                                {% endfor %}

                            </select>
                        
                        </div>

                        
                        <div id="bottom-wizard">
                            <button type="submit" name="process" class="btn btn-primary btn-lg btn-block">Proceed</button>
                        </div>
                    </form>
                </div>
                <!-- /Wizard container -->
                </div>
            </div><!-- /Row -->
        </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/customer/dashboard.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}
    

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">

            <div class="col-lg-4">
                <div id="left_form">
                    <!-- <h2>Welcome <span>To Your Food Booking Dashboard...</span></h2>
                    <p>Do you know you can eat any food from any popular food canteen in Abeokuta just from this App? </p>
                    <a href="{% url 'customer:category' %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Place an Order</a></br>
                    <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>
                    <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a>
                    
	                <a href="{% url 'customer:category' %}" class="btn_1 rounded mobile_btn yellow">Place an Order</a></br>
	                <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded mobile_btn yellow">Order History</a></br>
	                <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 rounded mobile_btn yellow">Customer Profile</a>
                    
                     -->


                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>

                    <a href="{% url 'customer:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                    <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a></br>
                    <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>

                    <a href="{% url 'customer:category' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1">Place Order</a></br>
	                <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Customer Profile</a></br>
	                <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 btn-block mobile_btn yellow">Order History</a></br>
					<br/><br/>
			    </div>
            </div>
            
        </div><!-- /Row -->
    </div><!-- /Form_container -->
    </div>

{% endblock content %}

app/templates/customer/editorder.html
{% extends 'registrationbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                    <div style="margin-top: -50px;">
                        <a href="{% url 'customer:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>

                        <a href="{% url 'customer:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1 btn-lg btn-block">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 btn-block mobile_btn yellow">Order History</a></br>
                    
                    </div> 
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>
                    <form method="POST" action="">
                        {% csrf_token %}

                     
                       
                        {% for forms in form_list %}

                        <div class="form-group col-sm-6"></div>

                            <div class="row form-row spacer mt-3 ml-3">

                                {{ forms }} <span>	&nbsp; </span><button class="btn btn-primary add-form-row">+</button>
                            
                            </div>

                       
                        
                            {% endfor %}
                            <div id="bottom-wizard">
                                <button type="submit" name="process" class="btn btn-primary btn-lg btn-block">Update</button>
                            </div>
                        </div>
                    </form>
                    
                </div>
                <!-- /Wizard container -->
                </div>
            </div><!-- /Row -->
        </div><!-- /Form_container -->
    </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script type="text/javascript">
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+)');
    var replacement = prefix + '-' + ndx;
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex, replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
}
function cloneMore(selector, prefix) {
    var newElement = $(selector).clone(true);
    var total = $('#id_' + prefix + '-TOTAL_FORMS').val();
    newElement.find(':input:not([type=button]):not([type=submit]):not([type=reset])').each(function() {
        var name = $(this).attr('name')
        if(name) {
            name = name.replace('-' + (total-1) + '-', '-' + total + '-');
            var id = 'id_' + name;
            $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        }
    });
    newElement.find('label').each(function() {
        var forValue = $(this).attr('for');
        if (forValue) {
          forValue = forValue.replace('-' + (total-1) + '-', '-' + total + '-');
          $(this).attr({'for': forValue});
        }
    });
    total++;
    $('#id_' + prefix + '-TOTAL_FORMS').val(total);
    $(selector).after(newElement);
    var conditionRow = $('.form-row:not(:last)');
    conditionRow.find('.btn.add-form-row')
    .removeClass('btn-success').addClass('btn-danger')
    .removeClass('add-form-row').addClass('remove-form-row')
    .html('-');
    return false;
}
function deleteForm(prefix, btn) {
    var total = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    if (total > 1){
        btn.closest('.form-row').remove();
        var forms = $('.form-row');
        $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
        for (var i=0, formCount=forms.length; i<formCount; i++) {
            $(forms.get(i)).find(':input').each(function() {
                updateElementIndex(this, prefix, i);
            });
        }
    }
    return false;
}
$(document).on('click', '.add-form-row', function(e){
    e.preventDefault();
    cloneMore('.form-row:last', 'form');
    return false;
});
$(document).on('click', '.remove-form-row', function(e){
    e.preventDefault();
    deleteForm('form', $(this));
    return false;
});
</script>

{% endblock content %}

app/templates/customer/payment.html
{% extends 'registrationbase.html' %}
{% load humanize %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% include 'registrationheader.html' %}

	<div class="container">
    <div id="form_container">
        <div class="row no-gutters">
            <div class="col-lg-4">
                <div id="left_form">
                    <h2 class="mb-0">Hi {{request.user.username|title}}
                        <span class="mb-0">
                        <hr/>KWIKY <p>... stressless delivery</p></span></h2>
                    
                    <div class="myspace">

                        <a href="{% url 'customer:dashboard' %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="mb-3 btn_1 rounded yellow purchase" target="_parent">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 rounded yellow purchase mb-2" target="_parent">Order History</a></br>

                        <a href="{% url 'customer:dashboard' %}" class="btn_1 mobile_btn  btn-block yellow btn-default mb-1 btn-lg btn-block">Dashboard</a></br>
                        <a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="btn_1 mb-1 btn-block mobile_btn yellow">Customer Profile</a></br>
                        <a href="{% url 'customer:order_history' request.user.id %}" class="btn_1 btn-block mobile_btn yellow"> Order History</a></br>
                   
                    </div>    
			    </div>
            </div>
            <div class="col-lg-8">
                <div id="wizard_container">
                    <div id="top-wizard">
                        <div id="progressbar"></div>
                        <span id="location"></span>
                    </div>
 <form>

    

   


      <table class="table table-responsive-sm table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Item</th>
            <th scope="col">Price</th>
            <th scope="col">Qty.</th>
          </tr>
        </thead>
        <tbody>
        {% for o in order.order.all  %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ o.subcategory.name }}</td>
                <td>₦{{ o.subcategory.price }} </td>
                <td>{{ o.quantity}}</td>
            </tr>

        {% endfor %}

        <tr>
           
            <td colspan="2">{{ order.package.name }}</td>
            <td>₦{{ order.package.price }}</td>
            <td>{{ order.package.duration|stringformat:'d'}} <span>m</span> </td>
           
        </tr>
         
        </tbody>
      </table>
        

    
   
   

    <!-- <script src="https://js.paystack.co/v1/inline.js"></script>

    <button type="button" class="btn btn-primary btn-block" onclick="payWithPaystack()">Pay Now - ₦ {{ order.total_price|intcomma }}</button>
     -->
  
        <script src="https://checkout.flutterwave.com/v3.js"></script>
        <button type="button" class="btn btn-primary btn-block" onclick="makePayment()">Pay Now - ₦ {{ order.total_price|intcomma }}</button>
        <a href="{% url 'customer:order_edit' order.id %}"><button type="button" class="btn mt-3 btn-danger btn-block">Edit Order Items</button></a>
        <a href="{% url 'customer:info_edit' order.id %}"><button type="button" class="btn mt-3 btn-success btn-block">Edit Order Info</button></a>
   
     
   
</form>
 
<!-- <script>
    function payWithPaystack(){
      var handler = PaystackPop.setup({
        //key: 'pk_live_1e13cd69bd7ecb3587a71e33ae19b29428d1da0f',  
        key: 'pk_test_61f3bb31b892b386b84607cec15c8dcc882c40d7',
        email: '{{ order.user.email }}',
        amount:  '{{ order.total_price }}' * 100,
        currency: "NGN",
        ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
        firstname: '{{ order.processorder.user.first_name|title }}',
        lastname: '{{ order.processorder.user.last_name|title }}',
        // label: "Optional string that replaces customer email"
        metadata: {
           custom_fields: [
              {
                  display_name: "{{ order.user.last_name|title }}",
                  variable_name: "{{ order.user.profilecustomer.phone_number }}",
                  value: "{{ order.user.profilecustomer.phone_number }}"
              }
           ]
        },
        callback: function(response){
            alert('success. transaction ref is ' + response.reference);
            window.location.replace("{% url 'customer:successpayment' order.id %}");
            
        },
        onClose: function(){
            alert('window closed');
        }
      });
      handler.openIframe();
    }
  </script> -->

  <script>
    function makePayment() {
      FlutterwaveCheckout({
        public_key: "FLWPUBK-81e2cf995d851f5651ad46973477e845-X",
        tx_ref: "{{ order.ref_code }}",
        amount: "{{order.total_price }}",
        currency: "NGN",
        payment_options: "banktransfer, account, 1voucher, card, ussd, payattitude",
        redirect_url: // specified redirect URL
          "{% url 'customer:successpayment' order.id %}",
       meta: {
          consumer_id: "{{ order.user.id }}",
          consumer_mac: "92a3-912ba-1192a",
        },
        customer: {
          email: "{{ order.user.email }}",
          phone_number: "{{ order.user.profilecustomer.phone_number }}",
          name: "{{ order.user.get_full_name|title }}",


          
        },
        callback: function (data) {
          console.log(data);
        },
        onclose: function() {
          // close modal
          alert('window closed');
        },
        customizations: {
          title: "Kwiky Delivery App",
          description: "Payment for Food Delivery",
          logo: "https://delivery.nigeriaware.com/static/registration/img/kwiky_logo_final.png",
        },
      });
    }
  </script>


</div>
                <!-- /Wizard container -->
                </div>
            </div><!-- /Row -->
        </div><!-- /Form_container -->
    </div>



  {% endblock content %}