api/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework_jwt.views import obtain_jwt_token
from api.views import *

urlpatterns = [
    path('api-token-auth/', obtain_jwt_token, name='create-token'),
    #re_path('api/(?P<version>(v1|v2))/', include('music.urls'))
    path('auth/login/', LoginView.as_view(), name="auth-login"),
    path('auth/register/', RegisterUsers.as_view(), name="auth-register"),
    path('rest-auth/', include('rest_auth.urls')),
]

app/urls.py
from django.urls import include, path
from .views import general, customer, bike

urlpatterns = [
    path('home/', general.home, name='home'),
    path('', general.FrontPage, name='front_page'),
    
    path('logout', general.logout_user, name='user_logout'),
    path("login", general.login, name='userlogin'),


    path('bike/', include(([

        path('dashboard', bike.BikeDashboard, name='dashboard'),
        path('profile/<pk>', bike.BikeProfile, name='bike_profile'),
        path('orders', bike.DeliveryOrder, name='order_delivery'),
        path('ordersdetails/<pk>', bike.DetailsOrder, name='details'),
        path('orderaccept/<pk>', bike.AcceptOrder, name='accept_order'),
        path('ordercompleted/<pk>', bike.CompleteOrder, name='complete_order'),


   
      
    ], 'app'), namespace='bike')),

    path('customer/', include(([

        path('dashboard', customer.CustomerDashboard, name='dashboard'),
        path('profile/<pk>', customer.CustomerProfile, name='customer_profile'),
        path('order', customer.PlaceOrder, name='place_order'),
        path('ajax/load-subcategories/', customer.load_foodcategory, name='ajax_load_subcategories'),
        path('category', customer.AdCategory, name='category'),
        path('billing/<pk>', customer.MyBilling, name='billing'),
        path('payment/<pk>', customer.PaymentProcess, name='payment'),
        path('done/<pk>', customer.SuccessPayment, name='successpayment'),
        path('history/<pk>', customer.HistoryOrder, name='order_history'),
        path('edit/<pk>', customer.OrderEdit, name='order_edit'),
        path('info/<pk>', customer.InfoEdit, name='info_edit'),
        


        
       
       
    ], 'app'), namespace='customer')),
]

food/urls.py
from django.contrib import admin
from django.urls import include, path
from app.views import general, customer, bike
from django.conf.urls import url
from  django.contrib.auth import login
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('app.urls')),
    path('api/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('apiv1/', include('apiV1.urls')),
    path('apiv2/', include('appV2.urls')),
    path('admin/', admin.site.urls),
    path('accounts/signup/customer/', customer.CustomerSignUpView.as_view(), name='customer_signup'),
    path('accounts/signup/bike/', bike.BikeSignUpView.as_view(), name='bike_signup'),

    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
       auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(),name='password_reset_done'),
    #path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),
]



if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/frontbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Connect - Personal Portfolio Template</title>
    <link rel="icon" href="assets/icons/favicon.png" type="image/png" sizes="16x16">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Connect Multipurpose  Landing Page Template Template">
    <meta name="keywords" content="Connect HTML Template, Connect Landing Page Template,  Landing Page Template">
    <link href="{% static 'frontpage/assets/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800,900%7COpen+Sans:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'frontpage/assets/css/animate.css' %}"> <!-- Resource style -->
    <link rel="stylesheet" href="{% static 'frontpage/assets/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'frontpage/assets/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'frontpage/assets/css/ionicons.min.css' %}"> <!-- Resource style -->
    <link href="{% static 'frontpage/assets/css/stylesheet.css' %}" rel="stylesheet" type="text/css" media="all" />
  </head>
  <body class="boxed-layout">

  {% block content %}

  {% endblock content %}

    <!-- Footer -->
    <div class="footer">
        <div class="container">
        <div class="row text-center">
            <div class="col-lg-2 col-md-3 col-sm-12">
            <div class="footer-logo">
                <h2>C O N N E C T.</h2>
            </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
            <ul class="footer-menu">
                <li><a href="{% url 'bike_signup' %}">Sign Up Bike</a> </li>
                <li><a href="#main">Privacy</a> </li>
                <li><a href="#main">Terms</a> </li>
                <li><a href="#main">Contact</a> </li>
            </ul>
            </div>
            <div class="col-lg-4 col-md-3 col-sm-12">
            <div class="footer-links">
                <ul>
                <li><a href="#main"> <img class="img-fluid" src="assets/icons/i1.png" alt="Icon"> </a> </li>
                <li><a href="#main"> <img class="img-fluid" src="assets/icons/i2.png" alt="Icon"> </a> </li>
                <li><a href="#main"> <img class="img-fluid" src="assets/icons/i3.png" alt="Icon"> </a> </li>
                <li><a href="#main"> <img class="img-fluid" src="assets/icons/i4.png" alt="Icon"> </a> </li>
                </ul>
            </div>
            </div>
        </div>
        <!-- Scroll To Top -->
            <a id="back-top" class="back-to-top js-scroll-trigger" href="#main"></a>
        <!-- Scroll To Top Ends-->
        </div>
    </div>

    <!-- Jquery and Js Plugins -->
    <script src="assets/js/jquery-2.1.1.js"></script>
    <script src="assets/js/popper.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/jquery.validate.min.js"></script>
    <script src="assets/js/plugins.js"></script>
    <script src="assets/js/custom.js"></script>
  </body>
</html>

templates/frontnav.html
    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top wt-border">
        <div class="container">
          <a class="navbar-brand" href="#">Connect.</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto navbar-right">
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#main">Product</a></li>
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#features">Features</a></li>
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#reviews">Reviews</a></li>
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#pricing">Pricing</a></li>
              <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#faqs">FAQ</a></li>
              <li><a class="btn-nav js-scroll-trigger" href="#cta">Download</a></li>
            </ul>
          </div>
        </div>
    </nav>

templates/messages.html
{% for message in messages %}



        <div class="alert {{ message.tags }} alert-default" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
            <strong>{{ message }}</strong>
        </div>


{% endfor %}

templates/registrationbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="We Devlivery across major street in Abeokuta such as Food, Grocery, Market Goods(Food Stuff)">
    <meta name="author" content="Couone Technology Limited">
    <title>KWIKY | ...stressless delivery</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="{% static 'registration/img/kwiky_icon.jpg' %}" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="{% static 'registration/img/kwiky_icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="{% static 'registration/img/kwiky_icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="{% static 'registration/img/kwiky_icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="{% static 'registration/img/kwiky_icon.jpg' %}">
	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700&display=swap" rel="stylesheet">

    <!-- BASE CSS -->
    <link href="{% static 'registration/css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'registration/css/menu.css' %}" rel="stylesheet">
    <link href="{% static 'registration/css/style.css' %}" rel="stylesheet">
	<link href="{% static 'registration/css/vendors.css' %}" rel="stylesheet">

    <!-- YOUR CUSTOM CSS -->
    <link href="{% static 'registration/css/custom.css' %}" rel="stylesheet">
	
	<!-- MODERNIZR MENU -->
	<script src="{% static 'registration/js/modernizr.js' %}"></script>

	<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">



<style>
	.btn-primary {
		color: #fff;
		background-color: #2955a9;
		border-color: #2955a9;

	}
	.myspace{
		margin-top: -50px;
	}

	.badge-primary{
		color: #fff;
		background-color: #2955a9;
		border-color: #2955a9;

	}
	
	
</style>

</head>

<body>
	
	<div id="preloader">
		<div data-loader="circle-side"></div>
	</div><!-- /Preload -->
	
	<div id="loader_form">
		<div data-loader="circle-side-2"></div>
	</div><!-- /loader_form -->

	
	<!-- /Header -->
{% block content %}

{% endblock content %}

<!-- /container -->

<div class="container">
    <footer id="home" class="clearfix">
        <ul style="font-size: 9px; text-align: center;">
            {% if user.is_authenticated and request.user.is_customer %}
				<li>Hi, {{ request.user }} | <a class="animated_link"  href="{% url 'user_logout' %}">LOGOUT</a></li>
				<li><a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="animated_link">My Profile</a></li>
				<li><a href="{% url 'customer:category' %}" class="animated_link">Place Order</a></li>
				<li><a href="{% url 'customer:order_history' request.user.id %}" class="animated_link">Order History</a></li>
			
			{% elif not user.is_authenticated and request.user.is_customer %}
				<li><a class="btn btn-white login"  href="{% url 'userlogin' %}">LOGIN</a></li>
				<li><a href="{% url 'customer:category' %}" class="animated_link">Place an Order</a></li>
			
			{% elif user.is_authenticated and request.user.is_bike %}
				<li>Hi, {{ request.user }} | <a class="animated_link"  href="{% url 'user_logout' %}">LOGOUT</a></li>
				<li><a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="animated_link">My Profile</a></li>
				<li><a href="{% url 'bike:order_delivery' %}" class="animated_link">Orders</a></li>

			{% elif not user.is_authenticated and request.user.is_bike %}
				<li><a class="btn btn-white login"  href="{% url 'userlogin' %}">LOGIN</a></li>
			
			{% endif %}
			
			
        </ul>        
		<p style="text-align: center;">©  {% now "Y" %}</p>

    </footer>
    <!-- end footer-->
</div>
<!-- /container -->

<div class="cd-overlay-nav">
    <span></span>
</div>
<!-- /cd-overlay-nav -->
<div class="cd-overlay-content">
    <span></span>
</div>
<!-- /cd-overlay-content -->

	<!-- Modal terms -->
	<div class="modal fade" id="terms-txt" tabindex="-1" role="dialog" aria-labelledby="termsLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="termsLabel">Terms and conditions</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<p>Lorem ipsum dolor sit amet, in porro albucius qui, in <strong>nec quod novum accumsan</strong>, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus.</p>
					<p>Lorem ipsum dolor sit amet, in porro albucius qui, in nec quod novum accumsan, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus. Lorem ipsum dolor sit amet, <strong>in porro albucius qui</strong>, in nec quod novum accumsan, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus.</p>
					<p>Lorem ipsum dolor sit amet, in porro albucius qui, in nec quod novum accumsan, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus.</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn_1" data-dismiss="modal">Close</button>
				</div>
			</div>
			<!-- /.modal-content -->
		</div>
		<!-- /.modal-dialog -->
	</div>
	<!-- /.modal -->

	<!-- Modal info -->
	<div class="modal fade" id="more-info" tabindex="-1" role="dialog" aria-labelledby="more-infoLabel" aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered">
			<div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title" id="more-infoLabel">Frequently asked questions</h4>
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				</div>
				<div class="modal-body">
					<p>Lorem ipsum dolor sit amet, in porro albucius qui, in <strong>nec quod novum accumsan</strong>, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus.</p>
					<p>Lorem ipsum dolor sit amet, in porro albucius qui, in nec quod novum accumsan, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus. Lorem ipsum dolor sit amet, <strong>in porro albucius qui</strong>, in nec quod novum accumsan, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus.</p>
					<p>Lorem ipsum dolor sit amet, in porro albucius qui, in nec quod novum accumsan, mei ludus tamquam dolores id. No sit debitis meliore postulant, per ex prompta alterum sanctus, pro ne quod dicunt sensibus.</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn_1" data-dismiss="modal">Close</button>
				</div>
			</div>
			<!-- /.modal-content -->
		</div>
		<!-- /.modal-dialog -->
	</div>
	<!-- /.modal -->
	
	<!-- COMMON SCRIPTS -->
	<script src="{% static 'registration/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'registration/js/common_scripts.min.js' %}"></script>
	<script src="{% static 'registration/js/velocity.min.js' %}"></script>
	<script src="{% static 'registration/js/common_functions.js' %}"></script>

	<!-- Wizard script-->
	<script src="{% static 'registration/js/func_1.js' %}"></script>


<!-- Latest compiled and minified JavaScript -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>

<!-- (Optional) Latest compiled and minified JavaScript translation files -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>

</body>
</html>

templates/registrationheader.html
{% load static %}
<header>
		<div class="container">
		    <div class="row">
                <div class="col-3">
                    {% if user.is_authenticated and request.user.is_customer %}
                        <a href="{% url 'customer:dashboard' %}"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="178" height="45" class="d-none d-md-block"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="62" height="45" class="d-block d-md-none"></a>
                    {% elif not user.is_authenticated and request.user.is_customer %}
                        <a href="{% url 'userlogin' %}"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="178" height="45" class="d-none d-md-block"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="62" height="45" class="d-block d-md-none"></a>
                    {% elif user.is_authenticated and request.user.is_bike %}
                        <a href="{% url 'bike:dashboard' %}"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="178" height="45" class="d-none d-md-block"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="62" height="45" class="d-block d-md-none"></a>
                    {% elif not user.is_authenticated and request.user.is_bike %}
                        <a href="{% url 'userlogin' %}"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="178" height="45" class="d-none d-md-block"><img src="{% static 'registration/img/kwiky_logo_final.png' %}" alt="" width="62" height="45" class="d-block d-md-none"></a>                    
                    {% endif %}
                </div>

                <div class="col-9">
                    <div id="social">
                        <ul>
                            <li><a href="#0"><i class="icon-facebook"></i></a></li>
                            <li><a href="#0"><i class="icon-twitter"></i></a></li>
                            <li><a href="#0"><i class="icon-google"></i></a></li>
                            <li><a href="#0"><i class="icon-linkedin"></i></a></li>
                            

                        </ul>
                    </div>
                    <!-- /social -->
					<a href="#0" class="cd-nav-trigger">Menu<span class="cd-icon"></span></a>
					<!-- /menu button -->
                    <nav>
						<ul class="cd-primary-nav">
							{% if user.is_authenticated and request.user.is_customer %}
                                <li>Hi, {{ request.user }} | <a class="animated_link"  href="{% url 'user_logout' %}">LOGOUT</a></li>
                                <li><a href="{% url 'customer:dashboard' %}" class="animated_link">Dashboard</a></li>

                                <li><a href="{% url 'customer:customer_profile' request.user.profilecustomer.id %}" class="animated_link">My Profile</a></li>
                                <li><a href="{% url 'customer:category' %}" class="animated_link">Place Order</a></li>
                                <li><a href="{% url 'customer:order_history' request.user.id %}" class="animated_link">Order History</a></li>
                            
                            {% elif not user.is_authenticated and request.user.is_customer %}
                                <li><a class="btn btn-white login"  href="{% url 'userlogin' %}">LOGIN</a></li>
                                <li><a href="{% url 'customer:category' %}" class="animated_link">Place an Order</a></li>
                            
                            {% elif user.is_authenticated and request.user.is_bike %}
                                <li>Hi, {{ request.user }} | <a class="animated_link"  href="{% url 'user_logout' %}">LOGOUT</a></li>
                                <li><a href="{% url 'bike:dashboard' %}" class="animated_link">Dashboard</a></li>
                                <li><a href="{% url 'bike:bike_profile' request.user.profilebike.id %}" class="animated_link">My Profile</a></li>
                                <li><a href="{% url 'bike:order_delivery' %}" class="animated_link">Orders</a></li>


                            {% elif not user.is_authenticated and request.user.is_bike %}
                                <li><a class="btn btn-white login"  href="{% url 'userlogin' %}">LOGIN</a></li>
                            
                            {% endif %}
                        </ul>
					</nav>
					<!-- /menu -->
                </div>
            </div>
		</div>
		<!-- /container -->
	</header>